steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    dir: '.'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/qdt-text:$COMMIT_SHA',
      '-f', 'Dockerfile',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/qdt-text:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'qdt-text'
      - '--image'
      - 'gcr.io/$PROJECT_ID/qdt-text:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8000'

images:
  - 'gcr.io/$PROJECT_ID/qdt-text:$COMMIT_SHA' 