name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: qdt-api
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} .
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --timeout 300 \
          --min-instances 1 \
          --max-instances 10 \
          --port 8080 \
          --memory 512Mi \
          --cpu 1 \
          --set-env-vars="PORT=8080"

    - name: Tag Container for Docker Hub
      run: docker tag qdt-api:latest gcr.io/hip-informatics-446103-u3/qdt-api:latest 

    - name: Push Container to Docker Hub
      run: docker push gcr.io/hip-informatics-446103-u3/qdt-api:latest 

    - name: Test Container Locally
      run: |
        docker build -t qdt-api:latest .
        docker run -p 8080:8080 qdt-api:latest 